### ISSUE TITLE
  "errorMessage": "No matching processor for event.

### ISSUE THREAD

**Issue by henryzhang1984** [assertible/lambda-cloudwatch-slack#19]
lambda-cloudwatch-slack-0.1.2

1.when code deploy to aws ,cloudwatch log show:

No matching processor for event. [EventSubscriptionArn: arn:aws:sns:ap-southeast-1:426052853157:staging-asg:51e5c7bb-9436-43c6-8cd6-33fa7aa748d5]

2. failed to   make test in local
processing cloudwatch notification
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
make: *** [test] Error 1

**Comment by henryzhang1984** [comment]
![image](https://user-images.githubusercontent.com/2032608/29009287-954eea78-7b54-11e7-91ec-8bf3e70b8237.png)

**Comment by rozhok** [comment]
Same here. What should we tune?

**Comment by creichert** [comment]
@henryzhang1984 Your event seems to be going through SNS, but what service is sending the event? I think there are currently some limitations that the processor has to be pre-defined: https://github.com/assertible/lambda-cloudwatch-slack/blob/master/config.js#L11

I'm happy to check this out if you can post your (scrubbed) event.

**Comment by creichert** [comment]
@rozhok What does your event look like? 

IMO, we probably need a better way to have a default "catchall" type event.

**Comment by rozhok** [comment]
Here we go:
```{
  "Records": [
    {
      "EventSource": "aws:sns",
      "EventVersion": "1.0",
      "EventSubscriptionArn": "arn:aws:sns:eu-west-1:111111111111111:samlpe-alert:ff1e3698-7f85-4da2-a90e-13ad2afe30e0",
      "Sns": {
        "Type": "Notification",
        "MessageId": "0d7a65e4-435e-5ff1-8e80-37e6fba3ef4f",
        "TopicArn": "arn:aws:sns:eu-west-1:111111111111111:Sample-alert",
        "Subject": "ALARM: \"Sample Alert\" in EU - Ireland",
        "Message": "{\"AlarmName\":\"Sample Alert\",\"AlarmDescription\":null,\"AWSAccountId\":\"111111111111111\",\"NewStateValue\":\"ALARM\",\"NewStateReason\":\"Threshold Crossed: 1 datapoint [1446.0 (07/08/17 18:46:00)] was greater than or equal to the threshold (1000.0).\",\"StateChangeTime\":\"2017-08-07T18:51:41.602+0000\",\"Region\":\"EU - Ireland\",\"OldStateValue\":\"OK\",\"Trigger\":{\"MetricName\":\"RequestCount\",\"Namespace\":\"AWS/ApplicationELB\",\"StatisticType\":\"Statistic\",\"Statistic\":\"SUM\",\"Unit\":null,\"Dimensions\":[{\"name\":\"LoadBalancer\",\"value\":\"app/app/6892f491c9b95d3f\"}],\"Period\":300,\"EvaluationPeriods\":1,\"ComparisonOperator\":\"GreaterThanOrEqualToThreshold\",\"Threshold\":1000.0,\"TreatMissingData\":\"\",\"EvaluateLowSampleCountPercentile\":\"\"}}",
        "Timestamp": "2017-08-07T18:51:41.652Z",
        "SignatureVersion": "1",
        "Signature": "lol",
        "SigningCertUrl": "https://sns.eu-west-1.amazonaws.com/SimpleNotificationService-b95095beb82e8f6a0463n12jnkndswea.pem",
        "UnsubscribeUrl": "https://sns.eu-west-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:eu-west-1:111111111111111:Sample-alert:ff1e3698-7f85-4da2-a90e-13ad2afe30e0",
        "MessageAttributes": {}
      }
    }
  ]
}
```

**Comment by creichert** [comment]
We are working on this in #20

**Comment by henryzhang1984** [comment]
![image](https://user-images.githubusercontent.com/2032608/29051629-a4bb9624-7c16-11e7-9dab-ce12ec585285.png)

**Comment by CodyReichert** [comment]
Thanks @henryzhang1984 - I see 2 issues here:

1. The `ECONNREFUSED` error. Do you have a correct `UNENCRYPTED_HOOK_URL` value set in the `deploy.env` file when you deployed to lambda? That's only reason I can see that happening (becuase it did successfully matched a `CloudWatch` event).

2. In your original issue, you _did_ post the `no matching processor found for event`. That one will be fixed in #20. (It also seems like you've corrected the `EventSubscriptionArn` since then, so you should be able to go without number 2 above).

Can you double check the webhook URL you have configured? Does that all look correct?

**Comment by CodyReichert** [comment]
Hey all - we just released [v0.2.1](https://www.npmjs.com/package/lambda-cloudwatch-slack) that contains a 'catch-all' handler for events that don't have a matching processor. Now, SampleEvents and various things like should work.

@henryzhang1984 - I believe `ECONNREFUSED` is an issue with not having a correct Slack Hook URL, so if you're still having issues with that please open another issue and I'll check it out!

**Comment by henryzhang1984** [comment]
![image](https://user-images.githubusercontent.com/2032608/29198789-a647e898-7e79-11e7-87fc-0f1024e9b360.png)

**Comment by rozhok** [comment]
@CodyReichert thanks! Will test it soon.
