### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by henryzhang1984** [assertible/lambda-cloudwatch-slack#21]
![image](https://user-images.githubusercontent.com/2032608/29198812-dacf48b8-7e79-11e7-9a1d-6ef1ab73ec78.png)

**Comment by CodyReichert** [comment]
Hey @henryzhang1984 - thanks for opening :) First thing I see:

Does it work if you add `https://` to the front of the `UNENCRYPTED_HOOK_URL`?

I tried locally without `https://`, and I actually got `ECONNRESET` (slightly different, but very similar error). Let me know, happy to take a deeper look!

**Comment by henryzhang1984** [comment]
when I add https ,it works

**Comment by CodyReichert** [comment]
Awesome! So you're good to go with everything?

I'll close this, but feel free to re-open if you have any other issues.
