### ISSUE TITLE
Cannot read property '0' of undefined (Executed Test Event CloudWatch)

### ISSUE THREAD

**Issue by geodeveloper** [assertible/lambda-cloudwatch-slack#23]
Hi,

I've everything set-up correctly and before using the lambda function, I wanted to test it by creating a new test (from AWS Console) and selected the CloudWatch template, once executed it gives this error:

```
Cannot read property '0' of undefined
    at processEvent (/var/task/index.js:321:43)
    at exports.handler (/var/task/index.js:369:5)
```

Any clue?

**Comment by creichert** [comment]
If you're using the Lambda test function, and not providing a valid payload, that would be the problem. You can take an event's JSON out of the test suite and paste it directly into the Lambda test payload editor.

**Comment by geodeveloper** [comment]
Hi @creichert ,

Thank for the reply. With real logs it's working fine (tested), but as I previously said, if I test with the CloudWatch template (provided by AWS) it failed to work (I guess the payload it's different but since the template it's a basic CloudWatch I thought it would work and expected to receive a Generic Notification.

I tried to check the logs but it doesn't exist. On Log output there is a link to access the logs *"Click here to view the CloudWatch log group."*, but when I click it opens the CloudWatch logs page and says:

*There was an error loading Log Streams. Please try again by refreshing this page.*

Anyways, checked again the CloudWatch template, and it has this payload:

```
{
  "awslogs": {
    "data": "H4sIAAAAAAAAAHWPwQqCQBCGX0Xm7EFtK+smZBEUgXoLCdMhFtKV3akI8d0bLYmibvPPN3wz00CJxmQnTO41whwWQRIctmEcB6sQbFC3CjW3XW8kxpOpP+OC22d1Wml1qZkQGtoMsScxaczKN3plG8zlaHIta5KqWsozoTYw3/djzwhpLwivWFGHGpAFe7DL68JlBUk+l7KSN7tCOEJ4M3/qOI49vMHj+zCKdlFqLaU2ZHV2a4Ct/an0/ivdX8oYc1UVX860fQDQiMdxRQEAAA=="
  }
}
```

So I guess that's the problem, is not a complete CloudWatch log.

So I think everything is working good so far. Thanks again.
