### ISSUE TITLE
npm run deploy fails

### ISSUE THREAD

**Issue by ernievd** [assertible/lambda-cloudwatch-slack#43]
Running on Ubuntu Windows. All looks to be installed correctly.
 Here is my npm debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'deploy' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle lambda-cloudwatch-slack@0.3.0~predeploy: lambda-cloudwatch-slack@0.3.0
6 silly lifecycle lambda-cloudwatch-slack@0.3.0~predeploy: no script for predeploy, continuing
7 info lifecycle lambda-cloudwatch-slack@0.3.0~deploy: lambda-cloudwatch-slack@0.3.0
8 verbose lifecycle lambda-cloudwatch-slack@0.3.0~deploy: unsafe-perm in lifecycle true
9 verbose lifecycle lambda-cloudwatch-slack@0.3.0~deploy: PATH: /usr/share/npm/bin/node-gyp-bin:/mnt/c/Users/ernest.vanduyne/PycharmProjects/aurora-backup/lambda-cloudwatch-slack-master/node_modules/.bin:/home/erniev/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1804.2019.521.0_x64__79rhkp1fndgsc:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files/Amazon/AWSCLI/bin:/mnt/c/Program Files/PuTTY:/mnt/c/Program Files/dotnet:/mnt/c/Users/ernest.vanduyne/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/ernest.vanduyne/AppData/Local/JetBrains/PyCharm Community Edition 2019.1.1/bin:/mnt/c/Users/ernest.vanduyne/AppData/Local/Programs/Git/cmd:/snap/bin
10 verbose lifecycle lambda-cloudwatch-slack@0.3.0~deploy: CWD: /mnt/c/Users/ernest.vanduyne/PycharmProjects/aurora-backup/lambda-cloudwatch-slack-master
11 silly lifecycle lambda-cloudwatch-slack@0.3.0~deploy: Args: [ '-c', './scripts/deploy.sh' ]
12 silly lifecycle lambda-cloudwatch-slack@0.3.0~deploy: Returned: code: 1  signal: null
13 info lifecycle lambda-cloudwatch-slack@0.3.0~deploy: Failed to exec deploy script
14 verbose stack Error: lambda-cloudwatch-slack@0.3.0 deploy: `./scripts/deploy.sh`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid lambda-cloudwatch-slack@0.3.0
16 verbose cwd /mnt/c/Users/ernest.vanduyne/PycharmProjects/aurora-backup/lambda-cloudwatch-slack-master
17 error Linux 4.4.0-17763-Microsoft
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "deploy"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error lambda-cloudwatch-slack@0.3.0 deploy: `./scripts/deploy.sh`
22 error Exit status 1
23 error Failed at the lambda-cloudwatch-slack@0.3.0 deploy script './scripts/deploy.sh'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the lambda-cloudwatch-slack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ./scripts/deploy.sh
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs lambda-cloudwatch-slack
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls lambda-cloudwatch-slack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ramilexe** [comment]
Because you are on Windows. Deploy script works only on Linux and Mac

**Comment by TeoWneD** [comment]
Maybe it'll help, i had the same errors but above i had a permission issue from aws, and since its fixed i can deploy with no problem

**Comment by CodyReichert** [comment]
hey @ernievd thanks for reporting!

If you're still working on this and neither of those suggestions work for you please re-open this. Thank you :+1:
