### ISSUE TITLE
how to send notification on a particular slack channel linked to a webhookurl url

### ISSUE THREAD

**Issue by rahulkumartandf** [assertible/lambda-cloudwatch-slack#56]
Hi,
I have multiple channels for a single slack Webhook.
how to i send the notification on a particular channel. i didn't see any variable of that in .env file.

**Comment by rahulkumartandf** [comment]
Hi I have multiple channels for a single slack Webhook.
how to i send the notification on a particular channel. i didn't see any variable of that in .env file.

**Comment by CodyReichert** [comment]
Hey @rahulkumartandf - we don't support setting a specific channel right now, however, someone opened #48 which adds that support and we will try to get that reviewed and merged asap.

For now you would have to create a new webhook URL for the specific channel.
