### ISSUE TITLE
When Triggering AWS CloudWatch Alarm: errorMessage "no matching processor for event"

### ISSUE THREAD

**Issue by smith-quinn** [assertible/lambda-cloudwatch-slack#7]
-I followed the README.txt. The "make deploy" was successful. 
-I created the SNS topic.
-I created the SNS subscription.
-I ran a test trigger using the github test CloudWatch notification template. That was successful.
-I added my lambda function to the CloudWatch Alarm.

Now when I force an alarm to fire off, I see that the SNS was received. The correct template is chosen, but i get the following message in my CloudWatch logs:

{
    "errorMessage": "no matching processor for event"
}

Where do I go from here? Please let me know if you have any suggestions for me.

**Comment by CodyReichert** [comment]
For what it's worth, the error is coming from here: https://github.com/assertible/lambda-cloudwatch-slack/blob/master/index.js#L270-L292

It gets to that point when the event ARN does not match one of those cases (beanstalk, cloudwatch, codedeploy, elasticache, and autoscaling).

Do you know if your event should be matching up with one of those? If possible, see if you can paste the JSON event, or just the ARN, here.

**Comment by creichert** [comment]
@CodyReichert we should add debug there so we can get a relevant portion of the message

@smith-quinn is it possible for you to post the event and gives a short description of where it's coming from? Then, we can implement support for that CloudWatch event type

**Comment by smith-quinn** [comment]
I'm using CloudWatch alarm's fire off the lambda function in the case of an alarm. 

  else if(eventSubscriptionArn.indexOf(config.services.cloudwatch.match_text) > -1 || eventSnsSubject.indexOf(config.services.cloudwatch.match_text) > -1 || eventSnsMessage.indexOf(config.services.cloudwatch.match_text) > -1){
    console.log("processing cloudwatch notification");
    slackMessage = handleCloudWatch(event,context);

As I mentioned, when I fire off the CloudWatch template from the github test directory, it sends it successfully to my Slack channel..

My Test Logs:
2017-01-04T19:08:25.433Z	sns received:
2017-01-04T19:08:25.434Z	processing cloudwatch notification
2017-01-04T19:08:25.723Z	        message posted successfully

My Alarm Logs:
2017-01-04T19:42:40.193Z		sns received:
2017-01-04T19:42:40.195Z	
{
    "errorMessage": "no matching processor for event"
}

**Comment by CodyReichert** [comment]
@smith-quinn On the `master` branch there are some improvements to the "no matching processor for event message". It will tell us the event subscription ARN so we can get some more info on the service.

If you can, deploy the latest version and run the same event -- update us here with the new error.

**Comment by smith-quinn** [comment]
I deployed the latest version and ran the same event. Here is the output in my CloudWatch Logs:

2017-01-04T20:51:19.653Z	8b1674b5-d2bf-11e6-8061-cbd9575bebda
{
    "errorMessage": "No matching processor for event. [EventSubscriptionArn: arn:aws:sns:us-east-1:525690699542:CloudWatch-to-Slack:ad2b90bd-2ebd-4629-8ab0-84c23099e6c7]"
}

Let me know what you think.

**Comment by knowroozi** [comment]
I think the default for that case can be shortened to "CloudWatch" from "CloudWatchNotifications". I think when I added it, that was the actual name of my SNS topic.

**Comment by smith-quinn** [comment]
@knowroozi  You are saying because my SNS Topic name is CloudWatch-to-Slack?

**Comment by knowroozi** [comment]
@smith-quinn yeah the string in the config file is tested against the subject, topic and subscription name of the SNS .. if that string is in there, it will satisfy the condition for whichever service you are looking at. 

The problem specifically i found with CloudWatch is that the SNS subject doesn't consistently have the AWS service name in it like ElastiCache or CodeDeploy

**Comment by smith-quinn** [comment]
That worked! 

Changed topic name to just CloudWatch, and i updated the value for services.cloudwatch.match_text to be CloudWatch.

Thank you @knowroozi

**Comment by CodyReichert** [comment]
Oh awesome, glad you got it working -- thanks @knowroozi.

Is there anything here I can do to have this supported in the lib itself? Feel free to open a PR too!

**Comment by henryzhang1984** [comment]
@CodyReichert 
![image](https://user-images.githubusercontent.com/2032608/29051575-4f91dbc2-7c16-11e7-8e9e-d2880b9ef884.png)

**Comment by CodyReichert** [comment]
[v0.2.1](https://www.npmjs.com/package/lambda-cloudwatch-slack), just released, contains a 'catch-all' handler for events that don't have a matching processor. Now, SampleEvents and various things like should work.

This should be fixed, so I'm going to close this, but feel free to re-open if you're still having issues.

@henryzhang1984 - see [this comment](https://github.com/assertible/lambda-cloudwatch-slack/issues/19#issuecomment-321699071) regarding your issue
